DROP TABLE GARANTIA;
DROP TABLE MANUTENCAO;
DROP TABLE EMPRESTIMO;
DROP TABLE ATIVO;
DROP TABLE STATUS;
DROP TABLE LOGIN;
DROP TABLE USUARIOS_SISTEMA;
DROP TABLE PERFIL;
DROP TABLE FUNCIONARIO;



CREATE TABLE PERFIL (
ID int,
DESCRICAO varchar (30),
CRIADO_POR int,
MODIFICADO_POR int,
DT_CRICAO DATETIME,
DT_MODIFICAO DATETIME
);

CREATE TABLE FUNCIONARIO (
ID int,
NOME varchar (30),
CARGO varchar (30),
CRIADO_POR int,
MODIFICADO_POR int,
DT_CRICAO DATETIME,
DT_MODIFICAO DATETIME
);

CREATE TABLE USUARIOS_SISTEMA (
ID int,
ID_PERFIL int,
SENHA varchar (30),
CRIADO_POR int,
MODIFICADO_POR int,
DT_CRICAO DATETIME,
DT_MODIFICAO DATETIME
);

CREATE TABLE LOGIN ( 
ID int,
DT_ACESSO DATETIME
);

CREATE TABLE STATUS (
ID int ,
DESCRICAO varchar (30),
CRIADO_POR int,
MODIFICADO_POR int,
DT_CRICAO DATETIME,
DT_MODIFICAO DATETIME
);

CREATE TABLE ATIVO (
ID int,
DESCRICAO varchar (30),
FABRICANTE varchar (30),
DT_COMPRA DATE,
VL_COMPRA int,
VL_DEPRECIADO int,
ID_STATUS int,
CRIADO_POR int,
MODIFICADO_POR int,
DT_CRICAO DATETIME,
DT_MODIFICAO DATETIME
);

CREATE TABLE EMPRESTIMO (
ID_FUNCIONARIO int,
ID_ATIVO int,
DT_EMPRESTIMO DATE,
DT_DEVOLUCAO DATE,
CRIADO_POR int,
MODIFICADO_POR int,
DT_CRICAO DATETIME,
DT_MODIFICAO DATETIME
);

CREATE TABLE MANUTENCAO (
ID int,
ID_ATIVO int,
DESCRICAO varchar (30),
DATA_CONCERTO DATE,
CRIADO_POR int,
MODIFICADO_POR int,
DT_CRICAO DATETIME,
DT_MODIFICAO DATETIME
);

CREATE TABLE GARANTIA (
ID int ,
ID_ATIVO int,
FORNECEDOR varchar (30),
CONTATO varchar (30),
CRIADO_POR int,
MODIFICADO_POR int,
DT_CRICAO DATETIME,
DT_MODIFICAO DATETIME
);


ALTER TABLE PERFIL ADD CONSTRAINT PK_PERFIL PRIMARY KEY (ID);
ALTER TABLE GARANTIA ADD CONSTRAINT PK_GARANTIA PRIMARY KEY (ID);
ALTER TABLE MANUTENCAO ADD CONSTRAINT PK_MANUTENCAO PRIMARY KEY (ID);
ALTER TABLE EMPRESTIMO ADD  CONSTRAINT PK_EMPRESTIMO PRIMARY KEY (ID_FUNCIONARIO,ID_ATIVO);
ALTER TABLE ATIVO ADD CONSTRAINT PK_ATIVO PRIMARY KEY (ID);
ALTER TABLE STATUS ADD CONSTRAINT PK_STATUS PRIMARY KEY (ID);
ALTER TABLE USUARIOS_SISTEMA ADD CONSTRAINT PK_USUARIOS_SISTEMA PRIMARY KEY (ID);
ALTER TABLE FUNCIONARIO ADD CONSTRAINT PK_FUNCIONARIO PRIMARY KEY(ID);
ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_FUNC FOREIGN KEY (CRIADO_POR) REFERENCES FUNCIONARIO (ID);
ALTER TABLE GARANTIA ADD CONSTRAINT FK_GARANTIA_FUNCIONARIO FOREIGN KEY (CRIADO_POR) REFERENCES FUNCIONARIO(ID);
ALTER TABLE GARANTIA ADD CONSTRAINT FK_GARANTIA_ATIVO FOREIGN KEY (ID_ATIVO) REFERENCES ATIVO(ID);
ALTER TABLE MANUTENCAO ADD CONSTRAINT FK_MANUTENCAO_FUNCIONARIO FOREIGN KEY (CRIADO_POR) REFERENCES FUNCIONARIO(ID);
ALTER TABLE MANUTENCAO ADD CONSTRAINT FK_MANUTENCAO_ATIVO FOREIGN KEY (ID_ATIVO) REFERENCES ATIVO(ID);
ALTER TABLE EMPRESTIMO ADD CONSTRAINT FK_EMP_FUNC FOREIGN KEY (CRIADO_POR) REFERENCES FUNCIONARIO(ID);
ALTER TABLE EMPRESTIMO ADD CONSTRAINT FK_EMP_ATIVO FOREIGN KEY (ID_ATIVO) REFERENCES ATIVO(ID);
ALTER TABLE ATIVO ADD CONSTRAINT FK_ATIVO_FUNCIONARIO FOREIGN KEY (CRIADO_POR) REFERENCES FUNCIONARIO(ID);
ALTER TABLE ATIVO ADD CONSTRAINT FK_ATIVO_STATUS FOREIGN KEY (ID_STATUS) REFERENCES STATUS(ID);
ALTER TABLE LOGIN ADD CONSTRAINT FK_LOGIN_USUARIO FOREIGN KEY (ID) REFERENCES USUARIOS_SISTEMA (ID);
ALTER TABLE USUARIOS_SISTEMA ADD CONSTRAINT FK_USR_SIS_FUNC FOREIGN KEY (ID) REFERENCES FUNCIONARIO(ID);
ALTER TABLE EMPRESTIMO ADD CONSTRAINT FK_EMP FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID);
ALTER TABLE USUARIOS_SISTEMA ADD CONSTRAINT FK_USF FOREIGN KEY (ID_PERFIL) REFERENCES PERFIL(ID);